from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "docs" / "artifacts"


TEAM = {
    "امین": "محمدامین پورمند",
    "محمدرضا": "محمدرضا آرمان پور",
    "محدثه": "محدثه حاتمی کیا",
}


JIRA_ROWS = [
    {
        "Issue Type": "Epic",
        "Summary": "تعریف پروژه و ارزش محصول",
        "Epic Name": "Project Definition",
        "Description": "تعریف مسئله، ذی‌نفعان، دامنه MVP، ارزش انسانی و ملی پروژه امدادیار.",
        "Assignee": TEAM["امین"],
        "Owner Role": "Project Lead",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 0",
        "Story Points": "6",
        "Original Estimate": "7h",
        "Time Spent": "7h",
        "Labels": "agile,scope,value",
        "Component/s": "Project Management",
        "Start Date": "2026-06-01",
        "Due Date": "2026-06-03",
        "Evidence Link": "docs/scope-change-record.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "ثبت شرح مسئله، ذی‌نفعان و ارزش اجتماعی",
        "Epic Name": "Project Definition",
        "Description": "تکمیل stakeholder register، ارزش اجتماعی و ملی، و توضیح اینکه سیستم جایگزین پزشک نیست.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Project Control & Metrics Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 0",
        "Story Points": "2",
        "Original Estimate": "3h",
        "Time Spent": "3h",
        "Labels": "stakeholders,value,ethics",
        "Component/s": "Project Control",
        "Start Date": "2026-06-01",
        "Due Date": "2026-06-03",
        "Evidence Link": "docs/stakeholder-register.md",
    },
    {
        "Issue Type": "Epic",
        "Summary": "مدل یادگیری ماشین و کنترل leakage",
        "Epic Name": "ML Model",
        "Description": "طراحی مدل فقط با داده‌های زمان تریاژ، ارزیابی v7، کنترل leakage و مستندسازی Model Card.",
        "Assignee": TEAM["امین"],
        "Owner Role": "ML & System Architect",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 1",
        "Story Points": "13",
        "Original Estimate": "18h",
        "Time Spent": "18h",
        "Labels": "ml,model-card,leakage",
        "Component/s": "ML",
        "Start Date": "2026-06-02",
        "Due Date": "2026-06-08",
        "Evidence Link": "docs/model-card.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "آماده‌سازی feature set قابل دفاع در زمان تریاژ",
        "Epic Name": "ML Model",
        "Description": "حذف داده‌های آینده و استفاده از علائم حیاتی، شکایت اصلی، سن و سوابق قابل پرسش.",
        "Assignee": TEAM["امین"],
        "Owner Role": "ML & System Architect",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 1",
        "Story Points": "5",
        "Original Estimate": "6h",
        "Time Spent": "6h",
        "Labels": "triage-time,data-leakage",
        "Component/s": "ML",
        "Start Date": "2026-06-02",
        "Due Date": "2026-06-03",
        "Evidence Link": "docs/model-card.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "آموزش و ارزیابی مدل v7",
        "Epic Name": "ML Model",
        "Description": "آموزش مدل عملیاتی v7 و ثبت متریک‌های AUC، Recall، Precision و FPR.",
        "Assignee": TEAM["امین"],
        "Owner Role": "ML & System Architect",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 3",
        "Story Points": "8",
        "Original Estimate": "9h",
        "Time Spent": "9h",
        "Labels": "v7,metrics,recall",
        "Component/s": "ML",
        "Start Date": "2026-06-06",
        "Due Date": "2026-06-08",
        "Evidence Link": "reports/model/metrics_v7.json",
    },
    {
        "Issue Type": "Epic",
        "Summary": "Backend و API محصول",
        "Epic Name": "Backend/API",
        "Description": "پیاده‌سازی FastAPI برای health، model-info، predict و feedback export.",
        "Assignee": TEAM["امین"],
        "Owner Role": "Backend/API Owner",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 2",
        "Story Points": "9",
        "Original Estimate": "8h",
        "Time Spent": "8h",
        "Labels": "fastapi,api,deploy",
        "Component/s": "Backend",
        "Start Date": "2026-06-04",
        "Due Date": "2026-06-15",
        "Evidence Link": "backend/main.py",
    },
    {
        "Issue Type": "Story",
        "Summary": "ساخت endpointهای /health، /model-info و /predict",
        "Epic Name": "Backend/API",
        "Description": "ارائه API قابل تست برای سلامت سرویس، اطلاعات مدل و پیش‌بینی بیمار با ورودی ناقص.",
        "Assignee": TEAM["امین"],
        "Owner Role": "Backend/API Owner",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 2",
        "Story Points": "5",
        "Original Estimate": "5h",
        "Time Spent": "5h",
        "Labels": "fastapi,predict",
        "Component/s": "Backend",
        "Start Date": "2026-06-04",
        "Due Date": "2026-06-05",
        "Evidence Link": "docs/api-documentation.md",
    },
    {
        "Issue Type": "Epic",
        "Summary": "رابط کاربری و PWA امدادیار",
        "Epic Name": "Frontend/PWA",
        "Description": "طراحی رابط فارسی، mobile-first، قابل نصب و قابل استفاده با مدل مرورگر بدون server local.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "UI/Documentation & QA Coordinator",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 4",
        "Story Points": "13",
        "Original Estimate": "13h",
        "Time Spent": "13h",
        "Labels": "frontend,pwa,mobile",
        "Component/s": "Frontend",
        "Start Date": "2026-06-09",
        "Due Date": "2026-06-21",
        "Evidence Link": "https://aminhatesprogramming.github.io/emergency-triage-mvp/",
    },
    {
        "Issue Type": "Story",
        "Summary": "طراحی UI فارسی و ساده‌سازی متن‌های کاربر",
        "Epic Name": "Frontend/PWA",
        "Description": "تبدیل عنوان محصول به امدادیار، حذف متن‌های گزارش‌گونه و ساده‌سازی عبارت‌های خروجی.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "UI/Documentation & QA Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 4",
        "Story Points": "5",
        "Original Estimate": "5h",
        "Time Spent": "5h",
        "Labels": "ux,fa,copywriting",
        "Component/s": "Frontend",
        "Start Date": "2026-06-20",
        "Due Date": "2026-06-21",
        "Evidence Link": "frontend/index.html",
    },
    {
        "Issue Type": "Story",
        "Summary": "تست سناریوی ورودی ناقص و بیمار بحرانی",
        "Epic Name": "Frontend/PWA",
        "Description": "تست public PWA روی موبایل و دسکتاپ با Chrome headless و سناریوهای critical/sparse.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "QA Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 5",
        "Story Points": "3",
        "Original Estimate": "3h",
        "Time Spent": "3h",
        "Labels": "qa,sparse-input,pwa",
        "Component/s": "QA",
        "Start Date": "2026-06-21",
        "Due Date": "2026-06-21",
        "Evidence Link": "scripts/check_public_pwa_cdp.js",
    },
    {
        "Issue Type": "Epic",
        "Summary": "کنترل پروژه، KPI و ریسک",
        "Epic Name": "Project Control",
        "Description": "ثبت KPIها، burndown، risk register، time tracking و شواهد Agile برای ارزیابی استاد.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Project Control & Metrics Coordinator",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 3",
        "Story Points": "12",
        "Original Estimate": "13h",
        "Time Spent": "13h",
        "Labels": "kpi,risk,burndown",
        "Component/s": "Project Control",
        "Start Date": "2026-06-08",
        "Due Date": "2026-06-21",
        "Evidence Link": "docs/agile-dashboard.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "آماده‌سازی KPI register و نمودار burndown",
        "Epic Name": "Project Control",
        "Description": "ثبت شاخص‌های AUC، Recall، Precision، FPR، وضعیت MVP/API/UI/docs و نمودار burndown.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Project Control & Metrics Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 3",
        "Story Points": "4",
        "Original Estimate": "4h",
        "Time Spent": "4h",
        "Labels": "kpi,burndown",
        "Component/s": "Project Control",
        "Start Date": "2026-06-08",
        "Due Date": "2026-06-08",
        "Evidence Link": "docs/kpi-register.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "تکمیل risk register و پاسخ ریسک‌ها",
        "Epic Name": "Project Control",
        "Description": "ثبت ریسک‌های مدل، داده، UX، deploy، همکاری تیمی و راهکارهای کاهش ریسک.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Project Control & Metrics Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 3",
        "Story Points": "3",
        "Original Estimate": "3h",
        "Time Spent": "3h",
        "Labels": "risk,mitigation",
        "Component/s": "Project Control",
        "Start Date": "2026-06-08",
        "Due Date": "2026-06-08",
        "Evidence Link": "docs/risk-register.md",
    },
    {
        "Issue Type": "Epic",
        "Summary": "مدیریت دانش و مستندات تحویل",
        "Epic Name": "Knowledge & Documentation",
        "Description": "ساخت knowledge base، گزارش نهایی، AI usage report، decision log، sprint notes و فایل‌های Word تحویل.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "Documentation Coordinator",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 5",
        "Story Points": "14",
        "Original Estimate": "16h",
        "Time Spent": "16h",
        "Labels": "knowledge-base,docs,ai-usage",
        "Component/s": "Documentation",
        "Start Date": "2026-06-10",
        "Due Date": "2026-06-21",
        "Evidence Link": "docs/knowledge-base/README.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "ثبت تصمیم‌های فنی و درس‌آموخته‌ها",
        "Epic Name": "Knowledge & Documentation",
        "Description": "ثبت technical decisions، lessons learned، meeting notes و علت تصمیم‌های معماری.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "Documentation Coordinator",
        "Priority": "High",
        "Status": "Done",
        "Sprint": "Sprint 5",
        "Story Points": "4",
        "Original Estimate": "4h",
        "Time Spent": "4h",
        "Labels": "decision-log,lessons,meetings",
        "Component/s": "Documentation",
        "Start Date": "2026-06-13",
        "Due Date": "2026-06-21",
        "Evidence Link": "docs/knowledge-base/technical-decisions.md",
    },
    {
        "Issue Type": "Story",
        "Summary": "آماده‌سازی فایل Word اطلاعات تکمیلی گروه",
        "Epic Name": "Knowledge & Documentation",
        "Description": "تهیه فایل Word شامل مشخصات تیم، اطلاعات تماس و شرح پروژه کمتر از ۵۰ کلمه برای ایلرن.",
        "Assignee": TEAM["امین"],
        "Owner Role": "Project Lead",
        "Priority": "Highest",
        "Status": "Done",
        "Sprint": "Sprint 5",
        "Story Points": "2",
        "Original Estimate": "2h",
        "Time Spent": "2h",
        "Labels": "submission,word,elearn",
        "Component/s": "Documentation",
        "Start Date": "2026-06-21",
        "Due Date": "2026-06-21",
        "Evidence Link": "docs/deliverables/ITPM_Group_Project_Info_Emdadyar.docx",
    },
    {
        "Issue Type": "Task",
        "Summary": "تایید ۹ بازخورد پرستار تریاژ",
        "Epic Name": "Product Validation",
        "Description": "پرسش از ۹ پرستار تریاژ یا فرد آشنا با تریاژ برای تایید/اصلاح بازخوردهای آماده درباره زبان خروجی، ورودی ناقص، هشدارها و نصب موبایل.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Stakeholder Feedback Coordinator",
        "Priority": "Highest",
        "Status": "In Progress",
        "Sprint": "Sprint 7",
        "Story Points": "5",
        "Original Estimate": "4h",
        "Time Spent": "2h",
        "Labels": "feedback,pilot,triage-nurse",
        "Component/s": "Validation",
        "Start Date": "2026-06-28",
        "Due Date": "2026-06-30",
        "Evidence Link": "docs/triage-nurse-feedback-confirmation.md",
    },
    {
        "Issue Type": "Task",
        "Summary": "جمع‌آوری بازخورد از ۵ کاربر پایلوت",
        "Epic Name": "Product Validation",
        "Description": "دریافت بازخورد از دانشجوی پزشکی/پرستاری، فرد آشنا با اورژانس و کاربران عمومی درباره وضوح UI و خروجی.",
        "Assignee": TEAM["محمدرضا"],
        "Owner Role": "Stakeholder Feedback Coordinator",
        "Priority": "High",
        "Status": "To Do",
        "Sprint": "Sprint 7",
        "Story Points": "5",
        "Original Estimate": "5h",
        "Time Spent": "0h",
        "Labels": "feedback,pilot,users",
        "Component/s": "Validation",
        "Start Date": "2026-06-28",
        "Due Date": "2026-07-05",
        "Evidence Link": "docs/knowledge-base/stakeholder-feedback-log.md",
    },
    {
        "Issue Type": "Task",
        "Summary": "گرفتن screenshot از Jira، GitHub Project و Knowledge Base",
        "Epic Name": "Final Evidence",
        "Description": "ثبت اسکرین‌شات از backlog، sprint board، time tracking، knowledge base و لینک عمومی امدادیار برای ارائه نهایی.",
        "Assignee": TEAM["محدثه"],
        "Owner Role": "Documentation & QA Coordinator",
        "Priority": "High",
        "Status": "To Do",
        "Sprint": "Sprint 6",
        "Story Points": "3",
        "Original Estimate": "3h",
        "Time Spent": "0h",
        "Labels": "screenshots,evidence,final",
        "Component/s": "Final Delivery",
        "Start Date": "2026-06-22",
        "Due Date": "2026-06-28",
        "Evidence Link": "docs/deliverables/",
    },
]


KNOWLEDGE_ROWS = [
    ["Project Home", "Overview", TEAM["امین"], "Done", "Sprint 0", "docs/project-management-plan.md", "تعریف پروژه، هدف، نقش‌ها و لینک‌های کلیدی"],
    ["Problem & Stakeholders", "Stakeholder Knowledge", TEAM["محمدرضا"], "Done", "Sprint 0", "docs/stakeholder-register.md", "ذی‌نفعان، ارزش اجتماعی و ملی، محدودیت اخلاقی"],
    ["Scope Change Record", "Decision Record", TEAM["امین"], "Done", "Sprint 0", "docs/scope-change-record.md", "تبدیل پروژه از صرفاً مدل به محصول امدادیار"],
    ["Architecture", "Technical Documentation", TEAM["امین"], "Done", "Sprint 2", "docs/architecture.md", "معماری API-first، PWA و مدل مرورگر"],
    ["API Documentation", "Technical Documentation", TEAM["امین"], "Done", "Sprint 2", "docs/api-documentation.md", "endpointها، payload نمونه و sparse input"],
    ["Model Card", "AI Governance", TEAM["امین"], "Done", "Sprint 3", "docs/model-card.md", "داده، متریک، leakage و محدودیت‌ها"],
    ["Risk Register", "Project Control", TEAM["محمدرضا"], "Done", "Sprint 3", "docs/risk-register.md", "ریسک‌ها، احتمال، اثر و پاسخ"],
    ["KPI Register", "Project Control", TEAM["محمدرضا"], "Done", "Sprint 3", "docs/kpi-register.md", "KPIهای مدل، محصول و فاز بعدی"],
    ["Agile Dashboard", "Project Control", TEAM["محمدرضا"], "Done", "Sprint 3", "docs/agile-dashboard.md", "burndown، velocity و وضعیت Sprintها"],
    ["Sprint Notes", "Team Knowledge", TEAM["محدثه"], "Done", "Sprint 5", "docs/knowledge-base/sprint-notes.md", "خروجی هر Sprint و شواهد deliverable"],
    ["Meeting Notes", "Team Knowledge", TEAM["محدثه"], "Done", "Sprint 5", "docs/knowledge-base/meeting-notes.md", "صورت‌جلسات و تصمیم‌های تیمی"],
    ["Technical Decisions", "Decision Record", TEAM["امین"], "Done", "Sprint 5", "docs/knowledge-base/technical-decisions.md", "تصمیم‌های مهم فنی و علت آنها"],
    ["AI Usage Report", "AI Governance", TEAM["محدثه"], "Done", "Sprint 5", "docs/ai-usage-report.md", "شفافیت استفاده از AI و نقش انسان"],
    ["Lessons Learned", "Retrospective", TEAM["محدثه"], "Done", "Sprint 5", "docs/lessons-learned.md", "یادگیری‌های فنی، مدیریتی و اخلاقی"],
    ["Triage Nurse Feedback Confirmation", "Validation", TEAM["محمدرضا"], "In Progress", "Sprint 7", "docs/triage-nurse-feedback-confirmation.md", "۹ بازخورد پیشنهادی پرستار تریاژ در انتظار تایید میدانی"],
    ["Stakeholder Feedback Log", "Validation", TEAM["محمدرضا"], "In Progress", "Sprint 6", "docs/knowledge-base/stakeholder-feedback-log.md", "ثبت بازخورد کاربران پایلوت و اقدامات اصلاحی"],
]


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_knowledge_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = ["Title", "Area", "Owner", "Status", "Sprint", "Evidence Link", "Description"]
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(KNOWLEDGE_ROWS)


def main() -> None:
    fields = [
        "Issue Type",
        "Summary",
        "Epic Name",
        "Description",
        "Assignee",
        "Owner Role",
        "Priority",
        "Status",
        "Sprint",
        "Story Points",
        "Original Estimate",
        "Time Spent",
        "Labels",
        "Component/s",
        "Start Date",
        "Due Date",
        "Evidence Link",
    ]
    write_csv(ARTIFACTS / "jira-import-issues.csv", fields, JIRA_ROWS)
    write_knowledge_csv(ARTIFACTS / "github-project-knowledge-items.csv")
    print(ARTIFACTS / "jira-import-issues.csv")
    print(ARTIFACTS / "github-project-knowledge-items.csv")


if __name__ == "__main__":
    main()
